# Generated by Django 4.2.18 on 2026-04-14 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Ex: A-000-067', max_length=20, unique=True)),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cellule',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone_whatsapp', models.CharField(help_text='Numéro WhatsApp (obligatoire)', max_length=30)),
                ('telephone_canada', models.CharField(blank=True, help_text='Numéro canadien', max_length=30, null=True)),
                ('province_origine', models.CharField(blank=True, help_text="Province d'origine (Burundi)", max_length=150, null=True)),
                ('ville_residence', models.CharField(blank=True, help_text='Ville de résidence', max_length=150, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('nom_pere', models.CharField(blank=True, max_length=200, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=200, null=True)),
                ('nom_conjoint', models.CharField(blank=True, max_length=200, null=True)),
                ('noms_enfants', models.TextField(blank=True, help_text='Noms des enfants, séparés par des virgules', null=True)),
                ('noms_freres_soeurs', models.TextField(blank=True, help_text='Noms des frères et sœurs', null=True)),
                ('personnes_en_charge', models.IntegerField(default=0)),
                ('nom_personne_referante', models.CharField(blank=True, max_length=200, null=True)),
                ('tel_personne_referante', models.CharField(blank=True, max_length=30, null=True)),
                ('email_personne_referante', models.CharField(blank=True, max_length=200, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'approbation"), ('APPROUVE', 'Approuvé'), ('SUSPENDU', 'Suspendu'), ('RADIE', 'Radié')], default='EN_ATTENTE', max_length=20)),
                ('role', models.CharField(choices=[('MEMBRE', 'Membre'), ('CHEF_CELLULE', 'Chef de Cellule'), ('CHARGE_APPROBATION', "Chargé d'Approbation"), ('CHARGE_FRAIS', 'Chargé des Frais'), ('COMPTABLE', 'Chargé de Comptabilité'), ('ADMIN', 'Administrateur')], default='MEMBRE', max_length=25)),
                ('date_demande_adhesion', models.DateTimeField(auto_now_add=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_affectation_cellule', models.DateTimeField(blank=True, null=True)),
                ('frais_adhesion_paye', models.BooleanField(default=False)),
                ('date_paiement_frais', models.DateTimeField(blank=True, null=True)),
                ('mot_de_passe_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('email_verifie', models.BooleanField(default=False)),
                ('telephone_verifie', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expire', models.DateTimeField(blank=True, null=True)),
                ('otp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_superadmin', models.BooleanField(default=False)),
                ('cellule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='sebc_app.cellule')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'db_table': 'membre',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code_iso', models.CharField(blank=True, max_length=3, null=True)),
                ('indicatif_tel', models.CharField(blank=True, max_length=10, null=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'db_table': 'pays',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeAyantDroit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'ayant droit",
                'verbose_name_plural': "Types d'ayants droits",
                'db_table': 'type_ayant_droit',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='NotificationGestionnaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recevoir_demandes_adhesion', models.BooleanField(default=False)),
                ('recevoir_cotisations', models.BooleanField(default=False)),
                ('recevoir_demandes_soutien', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_config', to='sebc_app.membre')),
            ],
            options={
                'db_table': 'notification_gestionnaire',
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='pays_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='sebc_app.pays'),
        ),
        migrations.AddField(
            model_name='membre',
            name='personne_referante',
            field=models.ForeignKey(blank=True, help_text='Le membre qui a référé cette personne', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_referes', to='sebc_app.membre'),
        ),
        migrations.AddField(
            model_name='cellule',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sebc_app.pays'),
        ),
        migrations.CreateModel(
            name='AyantDroit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayants_droits', to='sebc_app.membre')),
                ('type_lien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ayants_droits', to='sebc_app.typeayantdroit')),
            ],
            options={
                'verbose_name': 'Ayant droit',
                'verbose_name_plural': 'Ayants droits',
                'db_table': 'ayant_droit',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
