# Generated by Django 4.2.18 on 2026-04-14 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreAssociation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cle', models.CharField(help_text='Ex: delai_approbation_jours', max_length=100, unique=True)),
                ('libelle', models.CharField(help_text='Nom lisible du paramètre', max_length=200)),
                ('valeur', models.CharField(help_text='Valeur du paramètre', max_length=500)),
                ('type_valeur', models.CharField(choices=[('INT', 'Entier'), ('FLOAT', 'Décimal'), ('STRING', 'Texte'), ('BOOL', 'Oui/Non')], default='STRING', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(default='general', help_text='Catégorie de regroupement', max_length=100)),
                ('modifiable', models.BooleanField(default=True, help_text='Si False, seul un superadmin peut modifier')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'db_table': 'parametre_association',
                'ordering': ['categorie', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeSoutien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Ex: Décès du membre, Décès du conjoint', max_length=200, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, help_text='Montant du soutien en CAD', max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('nombre_temoins_requis', models.IntegerField(default=3, help_text='Nombre de témoins requis pour la réclamation')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de soutien',
                'verbose_name_plural': 'Types de soutien',
                'db_table': 'type_soutien',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('est_actif', models.BooleanField(default=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='sebc_app.pays')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'db_table': 'province',
                'ordering': ['pays__nom', 'nom'],
                'unique_together': {('nom', 'pays')},
            },
        ),
    ]
