# Generated by Django 4.2.18 on 2026-04-14 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebc_app', '0002_parametreassociation_typesoutien_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayantdroit',
            name='est_approuve',
            field=models.BooleanField(default=False, help_text="Approuvé par l'administration"),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_validation_parrain',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='parrain_valide',
            field=models.BooleanField(default=False, help_text='Le parrain a validé ce membre'),
        ),
        migrations.CreateModel(
            name='DocumentMembre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('PHOTO_IDENTITE', "Photo d'identité"), ('PIECE_IDENTITE', "Pièce d'identité"), ('PREUVE_RESIDENCE', 'Preuve de résidence'), ('AUTRE', 'Autre document')], max_length=30)),
                ('fichier', models.FileField(upload_to='documents/membres/%Y/%m/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False, help_text='Validé par un gestionnaire')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sebc_app.membre')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document_membre',
                'ordering': ['-date_upload'],
            },
        ),
    ]
