# Generated by Django 4.2.18 on 2026-04-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebc_app', '0003_ayantdroit_est_approuve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Identifiant technique (ex: membres, dashboard)', max_length=50, unique=True)),
                ('nom', models.CharField(help_text='Nom affiché dans la sidebar', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('icone', models.CharField(default='fas fa-cube', help_text='Classe FontAwesome (ex: fas fa-users)', max_length=80)),
                ('couleur', models.CharField(default='#60a5fa', help_text="Couleur de l'icône (hex)", max_length=30)),
                ('url', models.CharField(help_text='URL relative du module (ex: /membres/)', max_length=200)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage dans la sidebar")),
                ('est_actif', models.BooleanField(default=True)),
                ('visible_sidebar', models.BooleanField(default=True, help_text='Affiché dans la sidebar')),
                ('requiert_approbation', models.BooleanField(default=False, help_text='Accessible seulement aux membres approuvés')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'module',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='AccesModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MEMBRE', 'Membre'), ('CHEF_CELLULE', 'Chef de Cellule'), ('CHARGE_APPROBATION', "Chargé d'Approbation"), ('CHARGE_FRAIS', 'Chargé des Frais'), ('COMPTABLE', 'Chargé de Comptabilité'), ('ADMIN', 'Administrateur')], help_text='Rôle ayant accès à ce module', max_length=25)),
                ('peut_lire', models.BooleanField(default=True)),
                ('peut_ecrire', models.BooleanField(default=False)),
                ('peut_supprimer', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='sebc_app.module')),
            ],
            options={
                'verbose_name': 'Accès module',
                'verbose_name_plural': 'Accès modules',
                'db_table': 'acces_module',
                'ordering': ['module__ordre', 'role'],
                'unique_together': {('module', 'role')},
            },
        ),
    ]
