# Generated by Django 4.2.18 on 2026-04-14 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebc_app', '0004_module_accesmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationGroupe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('couleur_avatar', models.CharField(default='#128c7e', max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_crees', to='sebc_app.membre')),
            ],
            options={
                'verbose_name': 'Groupe de communication',
                'verbose_name_plural': 'Groupes de communication',
                'db_table': 'communication_groupe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypeMembre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Ex: Gestionnaire, Membre', max_length=100, unique=True)),
                ('niveau', models.CharField(blank=True, choices=[('NATIONAL', 'National'), ('CELLULE', 'Cellule')], help_text='Portée pour les gestionnaires : National ou Cellule', max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('peut_gerer_communication', models.BooleanField(default=False, help_text='Peut envoyer des communications de masse')),
                ('peut_approuver_membres', models.BooleanField(default=False)),
                ('peut_gerer_finances', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de membre',
                'verbose_name_plural': 'Types de membres',
                'db_table': 'type_membre',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='type_membre',
            field=models.ForeignKey(blank=True, help_text='Type de membre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='sebc_app.typemembre'),
        ),
        migrations.CreateModel(
            name='CommunicationGroupeMembre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_groupe', to='sebc_app.communicationgroupe')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_comm', to='sebc_app.membre')),
            ],
            options={
                'verbose_name': 'Membre de groupe',
                'verbose_name_plural': 'Membres de groupes',
                'db_table': 'communication_groupe_membre',
                'unique_together': {('groupe', 'membre')},
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.CharField(choices=[('individual', 'Membre individuel'), ('cellule', 'Cellule entière'), ('national', 'Tous les membres'), ('type_membre', 'Par type de membre'), ('custom_group', 'Groupe personnalisé')], default='individual', max_length=20)),
                ('direction', models.CharField(choices=[('out', 'Sortant'), ('in', 'Entrant')], default='out', max_length=5)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communication/attachments/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('delivered', 'Délivré'), ('read', 'Lu'), ('failed', 'Échoué')], default='sent', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='sebc_app.membre')),
                ('target_cellule', models.ForeignKey(blank=True, help_text='Pour scope=cellule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sebc_app.cellule')),
                ('target_group', models.ForeignKey(blank=True, help_text='Pour scope=custom_group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sebc_app.communicationgroupe')),
                ('target_membre', models.ForeignKey(blank=True, help_text='Pour scope=individual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_recus', to='sebc_app.membre')),
                ('target_type_membre', models.ForeignKey(blank=True, help_text='Pour scope=type_membre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sebc_app.typemembre')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
                'db_table': 'communication',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread_id', 'created_at'], name='communicati_thread__31e4ef_idx'), models.Index(fields=['sender', 'created_at'], name='communicati_sender__c611f3_idx')],
            },
        ),
    ]
