# Generated by Django 4.2.18 on 2026-04-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebc_app', '0005_communicationgroupe_typemembre_membre_type_membre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('room_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('join_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('live', 'En cours'), ('ended', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_crees', to='sebc_app.membre')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'db_table': 'meeting',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='sebc_app.meeting')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invites', to='sebc_app.membre')),
            ],
            options={
                'verbose_name': 'Invitation réunion',
                'verbose_name_plural': 'Invitations réunions',
                'db_table': 'meeting_invite',
                'unique_together': {('meeting', 'membre')},
            },
        ),
    ]
