# Generated by Django 4.2.18 on 2026-04-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sebc_app', '0006_meeting_meetinginvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='mobile_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
